apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-changed
  namespace: lasample
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx-new
        image: nginx:1.7.9
        ports:
        - containerPort: 80
